# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_integral')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_integral')
    _integral = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_integral', [dirname(__file__)])
        except ImportError:
            import _integral
            return _integral
        try:
            _mod = imp.load_module('_integral', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _integral = swig_import_helper()
    del swig_import_helper
else:
    import _integral
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def fVls2(V, s2, n, ElogV, VlogV0, Vmax):
    return _integral.fVls2(V, s2, n, ElogV, VlogV0, Vmax)
fVls2 = _integral.fVls2

def EVfV(V, s2, n, ElogV, VlogV0, Vmax, M):
    return _integral.EVfV(V, s2, n, ElogV, VlogV0, Vmax, M)
EVfV = _integral.EVfV

def EsgmfV(V, s2, n, ElogV, VlogV0, Vmax, M):
    return _integral.EsgmfV(V, s2, n, ElogV, VlogV0, Vmax, M)
EsgmfV = _integral.EsgmfV

def VsgmfV(V, s2, n, ElogV, VlogV0, Vmax, M, Esgm):
    return _integral.VsgmfV(V, s2, n, ElogV, VlogV0, Vmax, M, Esgm)
VsgmfV = _integral.VsgmfV

def fs2lV(s2, n, V):
    return _integral.fs2lV(s2, n, V)
fs2lV = _integral.fs2lV

def fs2alV(s2a, a, n, V):
    return _integral.fs2alV(s2a, a, n, V)
fs2alV = _integral.fs2alV

def fVls2a(V, s2, n, EVa, Vga, a, n0, Vmax):
    return _integral.fVls2a(V, s2, n, EVa, Vga, a, n0, Vmax)
fVls2a = _integral.fVls2a

def EVfVa(V, s2, n, EVa, Vga, a, n0, Vmax, M):
    return _integral.EVfVa(V, s2, n, EVa, Vga, a, n0, Vmax, M)
EVfVa = _integral.EVfVa

def EsgmfVa(V, s2, n, EVa, Vga, a, n0, Vmax, M):
    return _integral.EsgmfVa(V, s2, n, EVa, Vga, a, n0, Vmax, M)
EsgmfVa = _integral.EsgmfVa

def VsgmfVa(V, s2, n, EVa, Vga, a, n0, Vmax, M, Esgm):
    return _integral.VsgmfVa(V, s2, n, EVa, Vga, a, n0, Vmax, M, Esgm)
VsgmfVa = _integral.VsgmfVa

def ms2fs2a(s2a, a, n, V):
    return _integral.ms2fs2a(s2a, a, n, V)
ms2fs2a = _integral.ms2fs2a

def Vsmplfs2a(s2a, a, n, V, ms2):
    return _integral.Vsmplfs2a(s2a, a, n, V, ms2)
Vsmplfs2a = _integral.Vsmplfs2a

def z_score(p):
    return _integral.z_score(p)
z_score = _integral.z_score
# This file is compatible with both classic and new-style classes.


